version: "3"
services:
  bigtable-emulator:
    image: jscott22/bigtable-emulator
    command:
      [
        "-cf",
        "dev.test.cf1,dev.test.cf2,dev.test.otherFamily,dev.dev.cf1,dev.dev.cf2,dev.dev.otherFamily",
      ]
    ports:
      - "9035:9035"
    expose:
      - "9035"
  bigtable-test:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./cover:/app/cover
    depends_on:
      - bigtable-emulator
